name: InputredirectionForMac Builder

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Projeto
        uses: actions/checkout@v4

      - name: Criar Estrutura APP
        run: |
          mkdir -p build/InputredirectionForMac.app/Contents/MacOS
          mkdir -p build/InputredirectionForMac.app/Contents/Resources

      - name: Compilar Aplicativo
        run: |
          swiftc \
          -target x86_64-apple-macos11 \
          -framework Cocoa \
          -framework GameController \
          main.swift \
          -o build/InputredirectionForMac.app/Contents/MacOS/InputredirectionForMac

      - name: Criar Info.plist
        run: |
          cat > build/InputredirectionForMac.app/Contents/Info.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">

          <plist version="1.0">
          <dict>

              <key>CFBundleExecutable</key>
              <string>InputredirectionForMac</string>

              <key>CFBundleIdentifier</key>
              <string>com.bernaspl3.inputredirection</string>

              <key>CFBundleName</key>
              <string>InputredirectionForMac</string>

              <key>CFBundleVersion</key>
              <string>1.0</string>

              <key>CFBundlePackageType</key>
              <string>APPL</string>

              <key>LSMinimumSystemVersion</key>
              <string>11.0</string>

          </dict>
          </plist>
          EOF

      - name: Permissão Executável
        run: |
          chmod +x build/InputredirectionForMac.app/Contents/MacOS/InputredirectionForMac

      - name: Mostrar Arquivos
        run: |
          ls -R build

      - name: Criar DMG
        run: |
          hdiutil create \
          -volname "InputredirectionForMac" \
          -srcfolder build/InputredirectionForMac.app \
          -ov \
          -format UDZO \
          build/InputredirectionForMac.dmg

      - name: Upload APP
        uses: actions/upload-artifact@v4
        with:
          name: InputredirectionForMac-APP
          path: build/InputredirectionForMac.app

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: InputredirectionForMac-DMG
          path: build/InputredirectionForMac.dmg
